# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keijiban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='userid',
        ),
        migrations.AddField(
            model_name='tweet',
            name='twidata',
            field=models.TextField(default='NOTHING', verbose_name='tweet'),
        ),
    ]
