# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keijiban', '0002_auto_20161226_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='twilink',
            field=models.CharField(default='NOTHING', max_length=500, verbose_name='link'),
        ),
    ]
