# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keijiban', '0005_auto_20161227_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='twiurl',
            field=models.CharField(default='NOTHING', max_length=500, verbose_name='url'),
        ),
    ]
