# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import keijiban.models


class Migration(migrations.Migration):

    dependencies = [
        ('keijiban', '0006_tweet_twiurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='USERID',
            field=models.CharField(default='NOTHING', max_length=500, verbose_name=keijiban.models.Tweet),
        ),
    ]
