# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keijiban', '0007_auto_20161228_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='USERID',
            field=models.CharField(default='NOTHING', max_length=500, verbose_name='id'),
        ),
    ]
